[project]
name = "cnote-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.13",
    "python-multipart>=0.0.20",
    "uvicorn[standard]>=0.34.3",
]
